CREATE TABLE PURCHASEBUDGET(
ID NUMBER PRIMARY KEY,
YEAR NUMBER,
UNITCODE VARCHAR2(10),
UNITNAME VARCHAR2(100),
DEPTCODE VARCHAR2(20),
DEPTNAME VARCHAR2(100),
SUBJECTCODE VARCHAR2(20),
SUBJECTNAME VARCHAR2(100),
ITEMSCODE VARCHAR2(20),
ITEMSNAME VARCHAR2(100),
METHODCODE VARCHAR2(20),
METHODNAME VARCHAR2(100),
DETAILDESC VARCHAR2(1000),
PRICE NUMBER,
QUANTITY NUMBER,
AMOUNT NUMBER,
BUDGETUSE VARCHAR2(1000),
APPLYEDSUM NUMBER,
REMAIN NUMBER,
INPUTUSER VARCHAR2(20) default 'SYSTEM',
INPUTTIME DATE default SYSDATE,
UPDATEUSER VARCHAR2(20) default 'SYSTEM',
UPDATETIME DATE default SYSDATE,
REMARK VARCHAR2(1000)
)
-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE PURCHASEBUDGET
  IS '采购预算表';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN PURCHASEBUDGET.ID
  IS '唯一标识';
COMMENT ON COLUMN PURCHASEBUDGET.YEAR
  IS '年度';
COMMENT ON COLUMN PURCHASEBUDGET.UNITCODE
  IS '单位代码';
COMMENT ON COLUMN PURCHASEBUDGET.UNITNAME
  IS '单位名称';
COMMENT ON COLUMN PURCHASEBUDGET.DEPTCODE
  IS '科室代码';
COMMENT ON COLUMN PURCHASEBUDGET.DEPTNAME
  IS '科室名称';
COMMENT ON COLUMN PURCHASEBUDGET.SUBJECTCODE
  IS '科目代码';
COMMENT ON COLUMN PURCHASEBUDGET.SUBJECTNAME
  IS '科目名称';
COMMENT ON COLUMN PURCHASEBUDGET.ITEMSCODE
  IS '品目代码';
COMMENT ON COLUMN PURCHASEBUDGET.ITEMSNAME
  IS '品目名称';
COMMENT ON COLUMN PURCHASEBUDGET.METHODCODE
  IS '采购方式代码';
COMMENT ON COLUMN PURCHASEBUDGET.METHODNAME
  IS '采购方式名称';
COMMENT ON COLUMN PURCHASEBUDGET.DETAILDESC
  IS '详细要求';
COMMENT ON COLUMN PURCHASEBUDGET.PRICE
  IS '单价(元)';
COMMENT ON COLUMN PURCHASEBUDGET.QUANTITY
  IS '数量';
COMMENT ON COLUMN PURCHASEBUDGET.AMOUNT
  IS '总价(元)';
COMMENT ON COLUMN PURCHASEBUDGET.BUDGETUSE
  IS '用途';
COMMENT ON COLUMN PURCHASEBUDGET.APPLYEDSUM
  IS '已申请金额';
COMMENT ON COLUMN PURCHASEBUDGET.REMAIN
  IS '余额';
COMMENT ON COLUMN PURCHASEBUDGET.INPUTUSER
  IS '录入人';
COMMENT ON COLUMN PURCHASEBUDGET.INPUTTIME
  IS '录入时间';
COMMENT ON COLUMN PURCHASEBUDGET.UPDATEUSER
  IS '更新人';
COMMENT ON COLUMN PURCHASEBUDGET.UPDATETIME
  IS '更新时间';
COMMENT ON COLUMN PURCHASEBUDGET.REMARK
  IS '备注';