package cn.yangqun.common.model;

import cn.yangqun.common.model.base.BasePurchasebudget;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Purchasebudget extends BasePurchasebudget<Purchasebudget> {
	public static final Purchasebudget dao = new Purchasebudget().dao();
}
