package cn.yangqun.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMember<M extends BaseMember<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("ID", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("ID");
	}

	public M setSourceid(java.lang.Integer sourceid) {
		set("SOURCEID", sourceid);
		return (M)this;
	}
	
	public java.lang.Integer getSourceid() {
		return getInt("SOURCEID");
	}

	public M setParentid(java.lang.Integer parentid) {
		set("PARENTID", parentid);
		return (M)this;
	}
	
	public java.lang.Integer getParentid() {
		return getInt("PARENTID");
	}

	public M setRelationid(java.lang.Integer relationid) {
		set("RELATIONID", relationid);
		return (M)this;
	}
	
	public java.lang.Integer getRelationid() {
		return getInt("RELATIONID");
	}

	public M setCode(java.lang.String code) {
		set("CODE", code);
		return (M)this;
	}
	
	public java.lang.String getCode() {
		return getStr("CODE");
	}

	public M setName(java.lang.String name) {
		set("NAME", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("NAME");
	}

	public M setMembertype(java.lang.Integer membertype) {
		set("MEMBERTYPE", membertype);
		return (M)this;
	}
	
	public java.lang.Integer getMembertype() {
		return getInt("MEMBERTYPE");
	}

	public M setMembergroup(java.lang.Integer membergroup) {
		set("MEMBERGROUP", membergroup);
		return (M)this;
	}
	
	public java.lang.Integer getMembergroup() {
		return getInt("MEMBERGROUP");
	}

	public M setMembergrade(java.lang.Integer membergrade) {
		set("MEMBERGRADE", membergrade);
		return (M)this;
	}
	
	public java.lang.Integer getMembergrade() {
		return getInt("MEMBERGRADE");
	}

	public M setMemberlevel(java.lang.Integer memberlevel) {
		set("MEMBERLEVEL", memberlevel);
		return (M)this;
	}
	
	public java.lang.Integer getMemberlevel() {
		return getInt("MEMBERLEVEL");
	}

	public M setMemberstyle(java.lang.Integer memberstyle) {
		set("MEMBERSTYLE", memberstyle);
		return (M)this;
	}
	
	public java.lang.Integer getMemberstyle() {
		return getInt("MEMBERSTYLE");
	}

	public M setMemberstate(java.lang.Integer memberstate) {
		set("MEMBERSTATE", memberstate);
		return (M)this;
	}
	
	public java.lang.Integer getMemberstate() {
		return getInt("MEMBERSTATE");
	}

	public M setDepartmentcode(java.lang.String departmentcode) {
		set("DEPARTMENTCODE", departmentcode);
		return (M)this;
	}
	
	public java.lang.String getDepartmentcode() {
		return getStr("DEPARTMENTCODE");
	}

	public M setDepartmentname(java.lang.String departmentname) {
		set("DEPARTMENTNAME", departmentname);
		return (M)this;
	}
	
	public java.lang.String getDepartmentname() {
		return getStr("DEPARTMENTNAME");
	}

	public M setFlowcurrent(java.lang.String flowcurrent) {
		set("FLOWCURRENT", flowcurrent);
		return (M)this;
	}
	
	public java.lang.String getFlowcurrent() {
		return getStr("FLOWCURRENT");
	}

	public M setFlowprocess(java.lang.String flowprocess) {
		set("FLOWPROCESS", flowprocess);
		return (M)this;
	}
	
	public java.lang.String getFlowprocess() {
		return getStr("FLOWPROCESS");
	}

	public M setFirsttime(java.util.Date firsttime) {
		set("FIRSTTIME", firsttime);
		return (M)this;
	}
	
	public java.util.Date getFirsttime() {
		return get("FIRSTTIME");
	}

	public M setFinaltime(java.util.Date finaltime) {
		set("FINALTIME", finaltime);
		return (M)this;
	}
	
	public java.util.Date getFinaltime() {
		return get("FINALTIME");
	}

	public M setPapertime(java.util.Date papertime) {
		set("PAPERTIME", papertime);
		return (M)this;
	}
	
	public java.util.Date getPapertime() {
		return get("PAPERTIME");
	}

	public M setStamptime(java.util.Date stamptime) {
		set("STAMPTIME", stamptime);
		return (M)this;
	}
	
	public java.util.Date getStamptime() {
		return get("STAMPTIME");
	}

	public M setCaption(java.lang.String caption) {
		set("CAPTION", caption);
		return (M)this;
	}
	
	public java.lang.String getCaption() {
		return getStr("CAPTION");
	}

	public M setSummary(java.lang.String summary) {
		set("SUMMARY", summary);
		return (M)this;
	}
	
	public java.lang.String getSummary() {
		return getStr("SUMMARY");
	}

	public M setContent(java.lang.String content) {
		set("CONTENT", content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("CONTENT");
	}

	public M setDistrict(java.lang.String district) {
		set("DISTRICT", district);
		return (M)this;
	}
	
	public java.lang.String getDistrict() {
		return getStr("DISTRICT");
	}

	public M setAddress(java.lang.String address) {
		set("ADDRESS", address);
		return (M)this;
	}
	
	public java.lang.String getAddress() {
		return getStr("ADDRESS");
	}

	public M setPostcode(java.lang.String postcode) {
		set("POSTCODE", postcode);
		return (M)this;
	}
	
	public java.lang.String getPostcode() {
		return getStr("POSTCODE");
	}

	public M setContact(java.lang.String contact) {
		set("CONTACT", contact);
		return (M)this;
	}
	
	public java.lang.String getContact() {
		return getStr("CONTACT");
	}

	public M setPhone(java.lang.String phone) {
		set("PHONE", phone);
		return (M)this;
	}
	
	public java.lang.String getPhone() {
		return getStr("PHONE");
	}

	public M setFax(java.lang.String fax) {
		set("FAX", fax);
		return (M)this;
	}
	
	public java.lang.String getFax() {
		return getStr("FAX");
	}

	public M setMobile(java.lang.String mobile) {
		set("MOBILE", mobile);
		return (M)this;
	}
	
	public java.lang.String getMobile() {
		return getStr("MOBILE");
	}

	public M setEmail(java.lang.String email) {
		set("EMAIL", email);
		return (M)this;
	}
	
	public java.lang.String getEmail() {
		return getStr("EMAIL");
	}

	public M setUrl(java.lang.String url) {
		set("URL", url);
		return (M)this;
	}
	
	public java.lang.String getUrl() {
		return getStr("URL");
	}

	public M setAccountbank(java.lang.String accountbank) {
		set("ACCOUNTBANK", accountbank);
		return (M)this;
	}
	
	public java.lang.String getAccountbank() {
		return getStr("ACCOUNTBANK");
	}

	public M setAccountcode(java.lang.String accountcode) {
		set("ACCOUNTCODE", accountcode);
		return (M)this;
	}
	
	public java.lang.String getAccountcode() {
		return getStr("ACCOUNTCODE");
	}

	public M setAccountname(java.lang.String accountname) {
		set("ACCOUNTNAME", accountname);
		return (M)this;
	}
	
	public java.lang.String getAccountname() {
		return getStr("ACCOUNTNAME");
	}

	public M setAccountlevel(java.lang.Integer accountlevel) {
		set("ACCOUNTLEVEL", accountlevel);
		return (M)this;
	}
	
	public java.lang.Integer getAccountlevel() {
		return getInt("ACCOUNTLEVEL");
	}

	public M setAccountscore(java.lang.Integer accountscore) {
		set("ACCOUNTSCORE", accountscore);
		return (M)this;
	}
	
	public java.lang.Integer getAccountscore() {
		return getInt("ACCOUNTSCORE");
	}

	public M setAccountprice(java.math.BigDecimal accountprice) {
		set("ACCOUNTPRICE", accountprice);
		return (M)this;
	}
	
	public java.math.BigDecimal getAccountprice() {
		return get("ACCOUNTPRICE");
	}

	public M setUsername(java.lang.String username) {
		set("USERNAME", username);
		return (M)this;
	}
	
	public java.lang.String getUsername() {
		return getStr("USERNAME");
	}

	public M setPassword(java.lang.String password) {
		set("PASSWORD", password);
		return (M)this;
	}
	
	public java.lang.String getPassword() {
		return getStr("PASSWORD");
	}

	public M setPower(java.lang.String power) {
		set("POWER", power);
		return (M)this;
	}
	
	public java.lang.String getPower() {
		return getStr("POWER");
	}

	public M setNote(java.lang.String note) {
		set("NOTE", note);
		return (M)this;
	}
	
	public java.lang.String getNote() {
		return getStr("NOTE");
	}

}
