package cn.yangqun.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePurchasebudget<M extends BasePurchasebudget<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("ID", id);
		return (M)this;
	}
	
	public java.math.BigDecimal getId() {
		return get("ID");
	}

	public M setYear(Integer year) {
		set("YEAR", year);
		return (M)this;
	}
	
	public java.math.BigDecimal getYear() {
		return get("YEAR");
	}

	public M setUnitcode(java.lang.String unitcode) {
		set("UNITCODE", unitcode);
		return (M)this;
	}
	
	public java.lang.String getUnitcode() {
		return getStr("UNITCODE");
	}

	public M setUnitname(java.lang.String unitname) {
		set("UNITNAME", unitname);
		return (M)this;
	}
	
	public java.lang.String getUnitname() {
		return getStr("UNITNAME");
	}

	public M setDeptcode(java.lang.String deptcode) {
		set("DEPTCODE", deptcode);
		return (M)this;
	}
	
	public java.lang.String getDeptcode() {
		return getStr("DEPTCODE");
	}

	public M setDeptname(java.lang.String deptname) {
		set("DEPTNAME", deptname);
		return (M)this;
	}
	
	public java.lang.String getDeptname() {
		return getStr("DEPTNAME");
	}

	public M setSubjectcode(java.lang.String subjectcode) {
		set("SUBJECTCODE", subjectcode);
		return (M)this;
	}
	
	public java.lang.String getSubjectcode() {
		return getStr("SUBJECTCODE");
	}

	public M setSubjectname(java.lang.String subjectname) {
		set("SUBJECTNAME", subjectname);
		return (M)this;
	}
	
	public java.lang.String getSubjectname() {
		return getStr("SUBJECTNAME");
	}

	public M setItemscode(java.lang.String itemscode) {
		set("ITEMSCODE", itemscode);
		return (M)this;
	}
	
	public java.lang.String getItemscode() {
		return getStr("ITEMSCODE");
	}

	public M setItemsname(java.lang.String itemsname) {
		set("ITEMSNAME", itemsname);
		return (M)this;
	}
	
	public java.lang.String getItemsname() {
		return getStr("ITEMSNAME");
	}

	public M setMethodcode(java.lang.String methodcode) {
		set("METHODCODE", methodcode);
		return (M)this;
	}
	
	public java.lang.String getMethodcode() {
		return getStr("METHODCODE");
	}

	public M setMethodname(java.lang.String methodname) {
		set("METHODNAME", methodname);
		return (M)this;
	}
	
	public java.lang.String getMethodname() {
		return getStr("METHODNAME");
	}

	public M setDetaildesc(java.lang.String detaildesc) {
		set("DETAILDESC", detaildesc);
		return (M)this;
	}
	
	public java.lang.String getDetaildesc() {
		return getStr("DETAILDESC");
	}

	public M setPrice(double d) {
		set("PRICE", d);
		return (M)this;
	}
	
	public java.math.BigDecimal getPrice() {
		return get("PRICE");
	}

	public M setQuantity(double d) {
		set("QUANTITY", d);
		return (M)this;
	}
	
	public java.math.BigDecimal getQuantity() {
		return get("QUANTITY");
	}

	public M setAmount(double d) {
		set("AMOUNT", d);
		return (M)this;
	}
	
	public java.math.BigDecimal getAmount() {
		return get("AMOUNT");
	}

	public M setBudgetuse(java.lang.String budgetuse) {
		set("BUDGETUSE", budgetuse);
		return (M)this;
	}
	
	public java.lang.String getBudgetuse() {
		return getStr("BUDGETUSE");
	}

	public M setApplyedsum(java.math.BigDecimal applyedsum) {
		set("APPLYEDSUM", applyedsum);
		return (M)this;
	}
	
	public java.math.BigDecimal getApplyedsum() {
		return get("APPLYEDSUM");
	}

	public M setRemain(java.math.BigDecimal remain) {
		set("REMAIN", remain);
		return (M)this;
	}
	
	public java.math.BigDecimal getRemain() {
		return get("REMAIN");
	}

	public M setInputuser(java.lang.String inputuser) {
		set("INPUTUSER", inputuser);
		return (M)this;
	}
	
	public java.lang.String getInputuser() {
		return getStr("INPUTUSER");
	}

	public M setInputtime(java.util.Date inputtime) {
		set("INPUTTIME", inputtime);
		return (M)this;
	}
	
	public java.util.Date getInputtime() {
		return get("INPUTTIME");
	}

	public M setUpdateuser(java.lang.String updateuser) {
		set("UPDATEUSER", updateuser);
		return (M)this;
	}
	
	public java.lang.String getUpdateuser() {
		return getStr("UPDATEUSER");
	}

	public M setUpdatetime(java.util.Date updatetime) {
		set("UPDATETIME", updatetime);
		return (M)this;
	}
	
	public java.util.Date getUpdatetime() {
		return get("UPDATETIME");
	}

	public M setRemark(java.lang.String remark) {
		set("REMARK", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("REMARK");
	}

}
